INSERT INTO sport VALUES (2, 'DV', 'Aquatics', 'Diving');
INSERT INTO sport VALUES (9, 'SW', 'Aquatics', 'Swimming');
INSERT INTO sport VALUES (11, 'AR', 'Archery', 'Archery');
INSERT INTO sport VALUES (14, 'AT', 'Athletics', 'Athletics');
INSERT INTO sport VALUES (15, 'BD', 'Badminton', 'Badminton');
INSERT INTO sport VALUES (16, 'BK', 'Basketball', 'Basketball');
INSERT INTO sport VALUES (18, 'BX', 'Boxing', 'Boxing');
INSERT INTO sport VALUES (26, 'CR', 'Cycling', 'Cycling Road');
INSERT INTO sport VALUES (23, 'CT', 'Cycling', 'Cycling Track');
INSERT INTO sport VALUES (27, 'FE', 'Fencing', 'Fencing');
INSERT INTO sport VALUES (29, 'FB', 'Football', 'Football');
INSERT INTO sport VALUES (35, 'GT', 'Gymnastics', 'Trampoline');
INSERT INTO sport VALUES (38, 'HB', 'Handball', 'Handball');
INSERT INTO sport VALUES (40, 'HO', 'Hockey', 'Hockey');
INSERT INTO sport VALUES (41, 'JU', 'Judo', 'Judo');
INSERT INTO sport VALUES (42, 'RO', 'Rowing', 'Rowing');
INSERT INTO sport VALUES (43, 'SA', 'Sailing', 'Sailing');
INSERT INTO sport VALUES (44, 'SH', 'Shooting', 'Shooting');
INSERT INTO sport VALUES (45, 'TT', 'Table Tennis', 'Table Tennis');
INSERT INTO sport VALUES (46, 'TK', 'Taekwondo', 'Taekwondo');
INSERT INTO sport VALUES (47, 'TE', 'Tennis', 'Tennis');
INSERT INTO sport VALUES (48, 'TR', 'Triathlon', 'Triathlon');
INSERT INTO sport VALUES (49, 'VO', 'Volleyball', 'Beach volley.');
INSERT INTO sport VALUES (50, 'VO', 'Volleyball', 'Volleyball');
INSERT INTO sport VALUES (53, 'WL', 'Weightlifting', 'Weightlifting');
