INSERT INTO location VALUES (0, 'Australia', 'country', NULL);
INSERT INTO location VALUES (1, 'ACT', 'state', 0);
INSERT INTO location VALUES (2, 'New South Wales', 'state', 0);
INSERT INTO location VALUES (3, 'Northern Territory', 'state', 0);
INSERT INTO location VALUES (4, 'Queensland', 'state', 0);
INSERT INTO location VALUES (5, 'South Australia', 'state', 0);
INSERT INTO location VALUES (6, 'Tasmania', 'state', 0);
INSERT INTO location VALUES (7, 'Western Australia', 'state', 0);
INSERT INTO location VALUES (8, 'Victoria', 'state', 0);
INSERT INTO location VALUES (9, 'IOT', 'state', 0);
INSERT INTO location VALUES (10, 'Sydney', 'city', 2);
INSERT INTO location VALUES (11, 'Brisbane', 'city', 4);
INSERT INTO location VALUES (12, 'Melbourne', 'city', 8);
INSERT INTO location VALUES (13, 'Perth', 'city', 7);
INSERT INTO location VALUES (14, 'Adelaide', 'city', 5);
INSERT INTO location VALUES (15, 'Hobart', 'city', 6);
INSERT INTO location VALUES (16, 'Parramatta', 'city', 2);
INSERT INTO location VALUES (17, 'Sydney City', 'area', 10);
INSERT INTO location VALUES (18, 'Sydney North', 'area', 10);
INSERT INTO location VALUES (19, 'Sydney East', 'area', 10);
INSERT INTO location VALUES (20, 'Sydney Inner West', 'area', 10);
INSERT INTO location VALUES (21, 'CBD/ Millers Point', 'suburb', 17);
INSERT INTO location VALUES (22, 'Haymarket/ Pyrmont/ Ultimo', 'suburb', 17);
INSERT INTO location VALUES (23, 'Artarmon/ Chatswood/ Lane Cove', 'suburb', 18);
INSERT INTO location VALUES (24, 'Kirribilli / Milsons Point / Lavender Bay / McMahons Point', 'suburb', 18);
INSERT INTO location VALUES (25, 'Cremorne / Mosman / Neutral Bay', 'suburb', 18);
INSERT INTO location VALUES (26, 'Crows Nest / Nth Syd / St Leonards / Waverton', 'suburb', 18);
INSERT INTO location VALUES (27, 'Macquarie Park', 'suburb', 18);
INSERT INTO location VALUES (28, 'Manly', 'suburb', 18);
INSERT INTO location VALUES (29, 'Pittwater', 'suburb', 18);
INSERT INTO location VALUES (30, 'Bondi / Bondi Junction / Tamarama', 'suburb', 19);
INSERT INTO location VALUES (31, 'Bronte / Charing Cross', 'suburb', 19);
INSERT INTO location VALUES (32, 'Clovelly/Coogee/Kensington/Kingsford/Maroubra/Randwick', 'suburb', 19);
INSERT INTO location VALUES (33, 'Double Bay/ Edgecliff/ Paddington/ Rose Bay/ Woollahra', 'suburb', 19);
INSERT INTO location VALUES (34, 'Elizabeth Bay/ Kings Cross/ Potts Point/ Rushcutters Bay/ Woolloomooloo', 'suburb', 19);
INSERT INTO location VALUES (35, 'Darlinghurst/ Surry Hills', 'suburb', 19);
INSERT INTO location VALUES (36, 'Redfern/ Waterloo/ Zetland', 'suburb', 19);
INSERT INTO location VALUES (37, 'Chippendale/ Darlington', 'suburb', 19);
INSERT INTO location VALUES (38, 'Annandale/ Leichhardt', 'suburb', 20);
INSERT INTO location VALUES (39, 'Camperdown/ Forest Lodge/ Glebe', 'suburb', 20);
INSERT INTO location VALUES (40, 'Alexandria/ Enmore/ Erskineville/ Newtown', 'suburb', 20);
INSERT INTO location VALUES (41, 'Balmain/ Birchgrove/ Rozelle', 'suburb', 20);
INSERT INTO location VALUES (42, 'Ashfield/Lewisham/ Petersham/ Stanmore/Summer Hill', 'suburb', 20);
INSERT INTO location VALUES (43, 'Dulwich Hill/ Marrickville', 'suburb', 20);
INSERT INTO location VALUES (44, 'Melbourne CBD', 'suburb', 12);
INSERT INTO location VALUES (45, 'Carlton', 'suburb', 12);
INSERT INTO location VALUES (46, 'Brunswick', 'suburb', 12);
INSERT INTO location VALUES (47, 'Fitzroy', 'suburb', 12);
INSERT INTO location VALUES (48, 'Westgarth/etc', 'suburb', 12);
INSERT INTO location VALUES (50, 'Blacktown', 'city', 2);
INSERT INTO location VALUES (51, 'Penrith', 'city', 2);
INSERT INTO location VALUES (52, 'Canberra', 'city', 1);
INSERT INTO location VALUES (53, 'Fairfield', 'city', 2);
INSERT INTO location VALUES (55, 'Sydney', 'region', 10);
INSERT INTO location VALUES (57, 'Mulgoa', 'area', 53);
INSERT INTO location VALUES (58, 'Ginninderra', 'area', 52);
INSERT INTO location VALUES (59, 'Blaxland', 'area', 10);
INSERT INTO location VALUES (60, 'Croydon', 'area', 14);
INSERT INTO location VALUES (61, 'Griffith', 'area', 11);
INSERT INTO location VALUES (63, 'Penrith', 'suburb', NULL);
INSERT INTO location VALUES (64, 'Centennial Parklands', 'suburb', 10);
INSERT INTO location VALUES (65, 'Moore Park', 'suburb', 10);
INSERT INTO location VALUES (66, 'Darling Harbour', 'suburb', 10);
INSERT INTO location VALUES (67, 'Bennelong Point', 'suburb', 10);
INSERT INTO location VALUES (68, 'Bass Hill', 'suburb', 10);
INSERT INTO location VALUES (69, 'Woolloongabba', 'suburb', 11);
INSERT INTO location VALUES (70, 'Richmond', 'suburb', 12);
INSERT INTO location VALUES (71, 'Hindmarsh', 'suburb', 14);
INSERT INTO location VALUES (72, 'Sydney Olympic Park', 'suburb', 16);
INSERT INTO location VALUES (73, 'Rooty Hill', 'suburb', 50);
INSERT INTO location VALUES (74, 'Dean Park', 'suburb', 50);
INSERT INTO location VALUES (75, 'Cranebrook', 'suburb', 51);
INSERT INTO location VALUES (76, 'Bruce', 'suburb', 52);
INSERT INTO location VALUES (77, 'Cecil Park', 'suburb', 53);
INSERT INTO location VALUES (78, 'Horsley Park', 'suburb', 53);
INSERT INTO location VALUES (80, 'Darling Harbour, Exhibition Hall 4', 'eventvenue', 66);
INSERT INTO location VALUES (81, 'Darling Harbour, Exhibition Hall 5', 'eventvenue', 66);
INSERT INTO location VALUES (82, 'Darling Harbour, Sydney Convention Centre', 'eventvenue', 66);
INSERT INTO location VALUES (83, 'Darling Harbour, Sydney Entertainment Centre', 'eventvenue', 22);
INSERT INTO location VALUES (84, 'Darling Harbour, Sydney Exhibition Centre Halls 1 and 2', 'eventvenue', 66);
INSERT INTO location VALUES (85, 'Darling Harbour, Sydney Exhibition Centre, Halls 3 and 4', 'eventvenue', 66);
INSERT INTO location VALUES (86, 'Interstate Football, Adelaide, Hindmarsh Stadium ', 'eventvenue', 71);
INSERT INTO location VALUES (87, 'Interstate Football, Brisbane, Brisbane Cricket Ground', 'eventvenue', 69);
INSERT INTO location VALUES (88, 'Interstate Football, Canberra, Bruce Stadium', 'eventvenue', 76);
INSERT INTO location VALUES (89, 'Interstate Football, Melbourne, Melbourne Cricket Grounds', 'eventvenue', 70);
INSERT INTO location VALUES (90, 'Sydney East, Beach Volleyball Centre, Bondi', 'eventvenue', 30);
INSERT INTO location VALUES (91, 'Sydney East, Cycling Road Course, Centennial Parklands', 'eventvenue', 64);
INSERT INTO location VALUES (92, 'Sydney East, Marathon Course', 'eventvenue', 64);
INSERT INTO location VALUES (93, 'Sydney East, Sailing Marina, Rushcutters Bay', 'eventvenue', 34);
INSERT INTO location VALUES (94, 'Sydney East, Sydney Football Stadium', 'eventvenue', 65);
INSERT INTO location VALUES (95, 'Sydney East, Triathlon Course, Sydney Opera House', 'eventvenue', 67);
INSERT INTO location VALUES (96, 'Sydney Olympic Park Showground, Pavilion 2', 'eventvenue', 72);
INSERT INTO location VALUES (97, 'Sydney Olympic Park, All Venues', 'eventvenue', 72);
INSERT INTO location VALUES (98, 'Sydney Olympic Park, Archery Centre', 'eventvenue', 72);
INSERT INTO location VALUES (99, 'Sydney Olympic Park, Baseball Centre - Ride and Run ONLY', 'eventvenue', 72);
INSERT INTO location VALUES (100, 'Sydney Olympic Park, Baseball Centre, Sydney Showground', 'eventvenue', 72);
INSERT INTO location VALUES (101, 'Sydney Olympic Park, Olympic Stadium', 'eventvenue', 72);
INSERT INTO location VALUES (102, 'Sydney Olympic Park, Pavilion 2', 'eventvenue', 72);
INSERT INTO location VALUES (103, 'Sydney Olympic Park, Pavilion 3', 'eventvenue', 72);
INSERT INTO location VALUES (104, 'Sydney Olympic Park, Pavilion 4 ', 'eventvenue', 72);
INSERT INTO location VALUES (105, 'Sydney Olympic Park, Race Walks Course', 'eventvenue', 72);
INSERT INTO location VALUES (106, 'Sydney Olympic Park, State Hockey Centre', 'eventvenue', 72);
INSERT INTO location VALUES (107, 'Sydney Olympic Park, State Sports Centre', 'eventvenue', 72);
INSERT INTO location VALUES (108, 'Sydney Olympic Park, Sydney International Aquatic Centre', 'eventvenue', 72);
INSERT INTO location VALUES (109, 'Sydney Olympic Park, Sydney SuperDome', 'eventvenue', 72);
INSERT INTO location VALUES (110, 'Sydney Olympic Park, Tennis Centre Centre Court', 'eventvenue', 72);
INSERT INTO location VALUES (111, 'Sydney Olympic Park, The Dome', 'eventvenue', 72);
INSERT INTO location VALUES (112, 'Sydney West, Baseball Centre, Aquilina Reserve, Blacktown', 'eventvenue', 73);
INSERT INTO location VALUES (113, 'Sydney West, Dunc Gray Velodrome, Bankstown', 'eventvenue', 68);
INSERT INTO location VALUES (114, 'Sydney West, Equestrian Centre, Horsley Park', 'eventvenue', 78);
INSERT INTO location VALUES (115, 'Sydney West, Mountain Bike Course, Fairfield City Farm', 'eventvenue', 74);
INSERT INTO location VALUES (116, 'Sydney West, Slalom Course, Penrith Whitewater Stadium', 'eventvenue', 75);
INSERT INTO location VALUES (117, 'Sydney West, Softball Centre, Blacktown', 'eventvenue', 73);
INSERT INTO location VALUES (118, 'Sydney West, Sydney International Regatta Centre, Penrith Lakes', 'eventvenue', 63);
INSERT INTO location VALUES (119, 'Sydney West, Sydney International Shooting Centre, Cecil Park, Liverpool', 'eventvenue', 77);
