--
-- TOC entry 2302 (class 0 OID 2960498)
-- Dependencies: 219
-- Data for Name: country; Type: TABLE DATA; Schema: public; Owner: postgres
--
INSERT INTO country VALUES ('AFG', 'AF', 'Afghanistan');
INSERT INTO country VALUES ('ALB', 'AL', 'Albania');
INSERT INTO country VALUES ('ALG', 'DZ', 'Algeria');
INSERT INTO country VALUES ('ASA', 'AS', 'American Samoa*');
INSERT INTO country VALUES ('AND', 'AD', 'Andorra');
INSERT INTO country VALUES ('ANG', 'AO', 'Angola');
INSERT INTO country VALUES ('ANT', 'AG', 'Antigua and Barbuda');
INSERT INTO country VALUES ('ARG', 'AR', 'Argentina');
INSERT INTO country VALUES ('ARM', 'AM', 'Armenia');
INSERT INTO country VALUES ('ARU', 'AW', 'Aruba*');
INSERT INTO country VALUES ('AUS', 'AU', 'Australia');
INSERT INTO country VALUES ('AUT', 'AT', 'Austria');
INSERT INTO country VALUES ('AZE', 'AZ', 'Azerbaijan');
INSERT INTO country VALUES ('BAH', 'BS', 'Bahamas');
INSERT INTO country VALUES ('BRN', 'BH', 'Bahrain');
INSERT INTO country VALUES ('BAN', 'BD', 'Bangladesh');
INSERT INTO country VALUES ('BAR', 'BB', 'Barbados');
INSERT INTO country VALUES ('BLR', 'BY', 'Belarus');
INSERT INTO country VALUES ('BEL', 'BE', 'Belgium');
INSERT INTO country VALUES ('BIZ', 'BZ', 'Belize');
INSERT INTO country VALUES ('BER', 'BM', 'Bermuda*');
INSERT INTO country VALUES ('BEN', 'BJ', 'Benin');
INSERT INTO country VALUES ('BHU', 'BT', 'Bhutan');
INSERT INTO country VALUES ('BOL', 'BO', 'Bolivia');
INSERT INTO country VALUES ('BIH', 'BA', 'Bosnia and Herzegovina');
INSERT INTO country VALUES ('BOT', 'BW', 'Botswana');
INSERT INTO country VALUES ('BRA', 'BR', 'Brazil');
INSERT INTO country VALUES ('IVB', 'VG', 'British Virgin Islands');
INSERT INTO country VALUES ('BRU', 'BN', 'Brunei');
INSERT INTO country VALUES ('BUL', 'BG', 'Bulgaria');
INSERT INTO country VALUES ('BUR', 'BF', 'Burkina Faso');
INSERT INTO country VALUES ('BDI', 'BI', 'Burundi');
INSERT INTO country VALUES ('CAM', 'KH', 'Cambodia');
INSERT INTO country VALUES ('CMR', 'CM', 'Cameroon');
INSERT INTO country VALUES ('CAN', 'CA', 'Canada');
INSERT INTO country VALUES ('CPV', 'CV', 'Cape Verde');
INSERT INTO country VALUES ('CAY', 'KY', 'Cayman Islands*');
INSERT INTO country VALUES ('CAF', 'CF', 'Central African Republic');
INSERT INTO country VALUES ('CHA', 'TD', 'Chad');
INSERT INTO country VALUES ('CHI', 'CL', 'Chile');
INSERT INTO country VALUES ('CHN', 'CN', 'China');
INSERT INTO country VALUES ('COL', 'CO', 'Colombia');
INSERT INTO country VALUES ('COM', 'KM', 'Comoros');
INSERT INTO country VALUES ('CGO', 'CG', 'Congo');
INSERT INTO country VALUES ('COD', 'CD', 'Congo, Dem Rep');
INSERT INTO country VALUES ('COK', 'CK', 'Cook Islands');
INSERT INTO country VALUES ('CRC', 'CR', 'Costa Rica');
INSERT INTO country VALUES ('CIV', 'CI', 'Cote d''Ivoire');
INSERT INTO country VALUES ('CRO', 'HR', 'Croatia');
INSERT INTO country VALUES ('CUB', 'CU', 'Cuba');
INSERT INTO country VALUES ('CYP', 'CY', 'Cyprus');
INSERT INTO country VALUES ('CZE', 'CZ', 'Czech Republic');
INSERT INTO country VALUES ('DEN', 'DK', 'Denmark');
INSERT INTO country VALUES ('DJI', 'DJ', 'Djibouti');
INSERT INTO country VALUES ('DMA', 'DM', 'Dominica');
INSERT INTO country VALUES ('DOM', 'DO', 'Dominican Republic');
INSERT INTO country VALUES ('TLS', 'TL', 'East Timor (Timor-Leste)');
INSERT INTO country VALUES ('ECU', 'EC', 'Ecuador');
INSERT INTO country VALUES ('EGY', 'EG', 'Egypt');
INSERT INTO country VALUES ('ESA', 'SV', 'El Salvador');
INSERT INTO country VALUES ('GEQ', 'GQ', 'Equatorial Guinea');
INSERT INTO country VALUES ('ERI', 'ER', 'Eritrea');
INSERT INTO country VALUES ('EST', 'EE', 'Estonia');
INSERT INTO country VALUES ('ETH', 'ET', 'Ethiopia');
INSERT INTO country VALUES ('FIJ', 'FJ', 'Fiji');
INSERT INTO country VALUES ('FIN', 'FI', 'Finland');
INSERT INTO country VALUES ('FRA', 'FR', 'France');
INSERT INTO country VALUES ('GAB', 'GA', 'Gabon');
INSERT INTO country VALUES ('GAM', 'GM', 'Gambia');
INSERT INTO country VALUES ('GEO', 'GE', 'Georgia');
INSERT INTO country VALUES ('GER', 'DE', 'Germany');
INSERT INTO country VALUES ('GHA', 'GH', 'Ghana');
INSERT INTO country VALUES ('GRE', 'GR', 'Greece');
INSERT INTO country VALUES ('GRN', 'GD', 'Grenada');
INSERT INTO country VALUES ('GUM', 'GU', 'Guam');
INSERT INTO country VALUES ('GUA', 'GT', 'Guatemala');
INSERT INTO country VALUES ('GUI', 'GN', 'Guinea');
INSERT INTO country VALUES ('GBS', 'GW', 'Guinea-Bissau');
INSERT INTO country VALUES ('GUY', 'GY', 'Guyana');
INSERT INTO country VALUES ('HAI', 'HT', 'Haiti');
INSERT INTO country VALUES ('HON', 'HN', 'Honduras');
INSERT INTO country VALUES ('HKG', 'HK', 'Hong Kong*');
INSERT INTO country VALUES ('HUN', 'HU', 'Hungary');
INSERT INTO country VALUES ('ISL', 'IS', 'Iceland');
INSERT INTO country VALUES ('IND', 'IN', 'India');
INSERT INTO country VALUES ('INA', 'ID', 'Indonesia');
INSERT INTO country VALUES ('IRI', 'IR', 'Iran');
INSERT INTO country VALUES ('IRQ', 'IQ', 'Iraq');
INSERT INTO country VALUES ('IRL', 'IE', 'Ireland');
INSERT INTO country VALUES ('ISR', 'IL', 'Israel');
INSERT INTO country VALUES ('ITA', 'IT', 'Italy');
INSERT INTO country VALUES ('JAM', 'JM', 'Jamaica');
INSERT INTO country VALUES ('JPN', 'JP', 'Japan');
INSERT INTO country VALUES ('JOR', 'JO', 'Jordan');
INSERT INTO country VALUES ('KAZ', 'KZ', 'Kazakhstan');
INSERT INTO country VALUES ('KEN', 'KE', 'Kenya');
INSERT INTO country VALUES ('PRK', 'KP', 'Korea, North');
INSERT INTO country VALUES ('KOR', 'KR', 'Korea, South');
INSERT INTO country VALUES ('KUW', 'KW', 'Kuwait');
INSERT INTO country VALUES ('KGZ', 'KG', 'Kyrgyzstan');
INSERT INTO country VALUES ('LAO', 'LA', 'Laos');
INSERT INTO country VALUES ('LAT', 'LV', 'Latvia');
INSERT INTO country VALUES ('LIB', 'LB', 'Lebanon');
INSERT INTO country VALUES ('LES', 'LS', 'Lesotho');
INSERT INTO country VALUES ('LBR', 'LR', 'Liberia');
INSERT INTO country VALUES ('LBA', 'LY', 'Libya');
INSERT INTO country VALUES ('LIE', 'LI', 'Liechtenstein');
INSERT INTO country VALUES ('LTU', 'LT', 'Lithuania');
INSERT INTO country VALUES ('LUX', 'LU', 'Luxembourg');
INSERT INTO country VALUES ('MKD', 'MK', 'Macedonia');
INSERT INTO country VALUES ('MAD', 'MG', 'Madagascar');
INSERT INTO country VALUES ('MAW', 'MW', 'Malawi');
INSERT INTO country VALUES ('MAS', 'MY', 'Malaysia');
INSERT INTO country VALUES ('MDV', 'MV', 'Maldives');
INSERT INTO country VALUES ('MLI', 'ML', 'Mali');
INSERT INTO country VALUES ('MLT', 'MT', 'Malta');
INSERT INTO country VALUES ('MTN', 'MR', 'Mauritania');
INSERT INTO country VALUES ('MRI', 'MU', 'Mauritius');
INSERT INTO country VALUES ('MEX', 'MX', 'Mexico');
INSERT INTO country VALUES ('FSM', 'FM', 'Micronesia');
INSERT INTO country VALUES ('MDA', 'MD', 'Moldova');
INSERT INTO country VALUES ('MON', 'MC', 'Monaco');
INSERT INTO country VALUES ('MGL', 'MN', 'Mongolia');
INSERT INTO country VALUES ('MAR', 'MA', 'Morocco');
INSERT INTO country VALUES ('MOZ', 'MZ', 'Mozambique');
INSERT INTO country VALUES ('MYA', 'MM', 'Burma');
INSERT INTO country VALUES ('NAM', 'NA', 'Namibia');
INSERT INTO country VALUES ('NRU', 'NR', 'Nauru');
INSERT INTO country VALUES ('NEP', 'NP', 'Nepal');
INSERT INTO country VALUES ('NED', 'NL', 'Netherlands');
INSERT INTO country VALUES ('AHO', 'AN', 'Netherlands Antilles*');
INSERT INTO country VALUES ('NZL', 'NZ', 'New Zealand');
INSERT INTO country VALUES ('NCA', 'NI', 'Nicaragua');
INSERT INTO country VALUES ('NIG', 'NE', 'Niger');
INSERT INTO country VALUES ('NGR', 'NG', 'Nigeria');
INSERT INTO country VALUES ('NOR', 'NO', 'Norway');
INSERT INTO country VALUES ('OMA', 'OM', 'Oman');
INSERT INTO country VALUES ('PAK', 'PK', 'Pakistan');
INSERT INTO country VALUES ('PLW', 'PW', 'Palau');
INSERT INTO country VALUES ('PLE', 'PS', 'Palestine, Occupied Territories');
INSERT INTO country VALUES ('PAN', 'PA', 'Panama');
INSERT INTO country VALUES ('PNG', 'PG', 'Papua New Guinea');
INSERT INTO country VALUES ('PAR', 'PY', 'Paraguay');
INSERT INTO country VALUES ('PER', 'PE', 'Peru');
INSERT INTO country VALUES ('PHI', 'PH', 'Philippines');
INSERT INTO country VALUES ('POL', 'PL', 'Poland');
INSERT INTO country VALUES ('POR', 'PT', 'Portugal');
INSERT INTO country VALUES ('PUR', 'PR', 'Puerto Rico*');
INSERT INTO country VALUES ('QAT', 'QA', 'Qatar');
INSERT INTO country VALUES ('ROM', 'RO', 'Romania');
INSERT INTO country VALUES ('RUS', 'RU', 'Russia');
INSERT INTO country VALUES ('RWA', 'RW', 'Rwanda');
INSERT INTO country VALUES ('SKN', 'KN', 'Saint Kitts and Nevis');
INSERT INTO country VALUES ('LCA', 'LC', 'Saint Lucia');
INSERT INTO country VALUES ('VIN', 'VC', 'Saint Vincent and the Grenadines');
INSERT INTO country VALUES ('SAM', 'WS', 'Samoa');
INSERT INTO country VALUES ('SMR', 'SM', 'San Marino');
INSERT INTO country VALUES ('STP', 'ST', 'Sao Tome and Principe');
INSERT INTO country VALUES ('KSA', 'SA', 'Saudi Arabia');
INSERT INTO country VALUES ('SEN', 'SN', 'Senegal');
INSERT INTO country VALUES ('SCG', 'RS', 'Serbia');
INSERT INTO country VALUES ('SEY', 'SC', 'Seychelles');
INSERT INTO country VALUES ('SLE', 'SL', 'Sierra Leone');
INSERT INTO country VALUES ('SIN', 'SG', 'Singapore');
INSERT INTO country VALUES ('SVK', 'SK', 'Slovakia');
INSERT INTO country VALUES ('SLO', 'SI', 'Slovenia');
INSERT INTO country VALUES ('SOL', 'SB', 'Solomon Islands');
INSERT INTO country VALUES ('SOM', 'SO', 'Somalia');
INSERT INTO country VALUES ('RSA', 'ZA', 'South Africa');
INSERT INTO country VALUES ('ESP', 'ES', 'Spain');
INSERT INTO country VALUES ('SRI', 'LK', 'Sri Lanka');
INSERT INTO country VALUES ('SUD', 'SD', 'Sudan');
INSERT INTO country VALUES ('SUR', 'SR', 'Suriname');
INSERT INTO country VALUES ('SWZ', 'SZ', 'Swaziland');
INSERT INTO country VALUES ('SWE', 'SE', 'Sweden');
INSERT INTO country VALUES ('SUI', 'CH', 'Switzerland');
INSERT INTO country VALUES ('SYR', 'SY', 'Syria');
INSERT INTO country VALUES ('TPE', 'TW', 'Taiwan');
INSERT INTO country VALUES ('TJK', 'TJ', 'Tajikistan');
INSERT INTO country VALUES ('TAN', 'TZ', 'Tanzania');
INSERT INTO country VALUES ('THA', 'TH', 'Thailand');
INSERT INTO country VALUES ('TOG', 'TG', 'Togo');
INSERT INTO country VALUES ('TGA', 'TO', 'Tonga');
INSERT INTO country VALUES ('TRI', 'TT', 'Trinidad and Tobago');
INSERT INTO country VALUES ('TUN', 'TN', 'Tunisia');
INSERT INTO country VALUES ('TUR', 'TR', 'Turkey');
INSERT INTO country VALUES ('TKM', 'TM', 'Turkmenistan');
INSERT INTO country VALUES ('UGA', 'UG', 'Uganda');
INSERT INTO country VALUES ('UKR', 'UA', 'Ukraine');
INSERT INTO country VALUES ('UAE', 'AE', 'United Arab Emirates');
INSERT INTO country VALUES ('GBR', 'GB', 'United Kingdom');
INSERT INTO country VALUES ('USA', 'US', 'United States');
INSERT INTO country VALUES ('URU', 'UY', 'Uruguay');
INSERT INTO country VALUES ('UZB', 'UZ', 'Uzbekistan');
INSERT INTO country VALUES ('VAN', 'VU', 'Vanuatu');
INSERT INTO country VALUES ('VEN', 'VE', 'Venezuela');
INSERT INTO country VALUES ('VIE', 'VN', 'Vietnam');
INSERT INTO country VALUES ('ISV', 'VI', 'Virgin Islands*');
INSERT INTO country VALUES ('YEM', 'YE', 'Yemen');
INSERT INTO country VALUES ('ZAM', 'ZM', 'Zambia');
INSERT INTO country VALUES ('ZIM', 'ZW', 'Zimbabwe');
INSERT INTO country VALUES ('EUA', NULL, NULL);
INSERT INTO country VALUES ('URS', NULL, NULL);
INSERT INTO country VALUES ('ROU', NULL, NULL);
INSERT INTO country VALUES ('ZZX', NULL, NULL);
INSERT INTO country VALUES ('GDR', NULL, NULL);
INSERT INTO country VALUES ('BWI', NULL, NULL);
INSERT INTO country VALUES ('TCH', NULL, NULL);
INSERT INTO country VALUES ('IOP', NULL, NULL);
INSERT INTO country VALUES ('RU1', NULL, NULL);
INSERT INTO country VALUES ('EUN', NULL, NULL);
INSERT INTO country VALUES ('SRB', NULL, NULL);
INSERT INTO country VALUES ('BOH', NULL, NULL);
INSERT INTO country VALUES ('FRG', NULL, NULL);
INSERT INTO country VALUES ('ANZ', NULL, NULL);
INSERT INTO country VALUES ('YUG', NULL, NULL);
